#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# bsp or float (default: bsp)
yabai -m config layout                      bsp             \
                window_border               on              \
                focus_follows_mouse         off             \
                mouse_follows_focus         off             \
                window_placement            second_child    \
                window_topmost              off             \
                window_shadow               float           \
                window_opacity              on              \
                window_opacity_duration     0.15            \
                active_window_opacity       1.0             \
                normal_window_opacity       0.95            \
                window_border_width         2               \
                window_border_radius        11              \
                window_animation_duration   0.15            \
                normal_window_border_color  0xffe1e3e4      \
                active_window_border_color  0xff2a2f38      \
                insert_feedback_color       0xff9dd274      \
                split_ratio                 0.50            \
                auto_balance                off             \
                mouse_modifier              fn              \
                mouse_action1               move            \
                mouse_action2               resize          \
                mouse_drop_action           swap            \
                                                            \
                top_padding                 20              \
                bottom_padding              10              \
                left_padding                10              \
                right_padding               10              \
                window_gap                  8

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|LibreOffice|App Store|Alfred|Activity Monitor|Cisco Webex Meetings|VMware Remote Console|Zoiper5)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
yabai -m rule --add label="Outlook Preferences" app="^Microsoft Outlook$" title="Outlook Preferences" manage=off

# signals
yabai -m signal --add event=space_changed action="hs -c 'stackline.manager:update({forceRedraw = true})'"
# yabai -m signal --add event=window_focused action="hs -c \"yabaidirectcall.window_focused(\`printenv YABAI_WINDOW_ID\`)\""
# yabai -m signal --add event=application_activated action="hs -c \"yabaidirectcall.application_activated(\`printenv YABAI_PROCESS_ID\`)\""
# yabai -m signal --add event=window_resized action="hs -c \"yabaidirectcall.window_resized(\`printenv YABAI_WINDOW_ID\`)\""
# yabai -m signal --add event=window_moved action="hs -c \"yabaidirectcall.window_moved(\`printenv YABAI_WINDOW_ID\`)\""
# yabai -m signal --add event=window_destroyed action="hs -c \"yabaidirectcall.window_destroyed(\`printenv YABAI_WINDOW_ID\`)\""
