#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: bsp)
yabai -m config layout bsp
yabai -m config window_topmost off

# Set all padding and gaps to 10pt (default: 0)
padding_size=16
yabai -m config \
    top_padding     ${padding_size:=0} \
    bottom_padding  ${padding_size:=0} \
    left_padding    ${padding_size:=0} \
    right_padding   ${padding_size:=0} \
    window_gap      ${padding_size:=0}

# set mouse interaction modifier key (defualt: fn)
yabai -m config mouse_modifier alt

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus on

# modify windows shadows (default: on, options, on, off float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config \
    window_opacity          on      \
    active_window_opacity   1.0     \
    normal_window_opacity   0.90

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off
